---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: block.csi.k8s.io
  name: pv-block
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: block-csi
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: /dev/tmp/model
    volumeAttributes:
      blockfile: /dev/tmp/model
      fstype: /
